# Generated by Django 2.0.5 on 2018-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_resend', models.CharField(blank=True, max_length=10000000000000000000000, null=True)),
                ('image_to_process', models.CharField(blank=True, max_length=10000000000000000000000, null=True)),
                ('thresh', models.FloatField(blank=True, default='30')),
                ('scale', models.FloatField(blank=True, default='50')),
                ('length_dangling_arc', models.FloatField(blank=True, default='50')),
                ('section_size', models.FloatField(blank=True, default='1')),
            ],
        ),
    ]
