# Generated by Django 2.0.5 on 2018-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='id_name',
            field=models.CharField(blank=True, max_length=10000000000000000000000, null=True),
        ),
    ]
